### ISSUE TITLE
Tags de versão para compatibilidade com Boss

### ISSUE THREAD

**Issue by IagooCesaar** [ProjetoACBr/ACBr#7]
Olá pessoal!

Poderiam implementar neste repositório o controle de versões através das tags/releases?
Isto ajudaria a utilizar estes fontes nos projetos gerenciados pelo [Boss](https://github.com/HashLoad/boss)

![image](https://user-images.githubusercontent.com/12894025/193278270-3854c1aa-8d29-4340-9aef-5930f16c90f0.png)

![image](https://user-images.githubusercontent.com/12894025/193278013-ed6634ce-f595-43c2-9128-0c15f08fdd77.png)

**Comment by juliomar** [comment]
não é o projeto oficial, e o código aqui representando vem do svn do acbr

**Comment by IagooCesaar** [comment]
Mas de forma automática?
Ao replicar para o GitHub não poderia atualizar também as tags/releases?

**Comment by claytonaalves** [comment]
> Mas de forma automática? Ao replicar para o GitHub não poderia atualizar também as tags/releases?

@IagooCesaar o ACBr não controla número de versão, nem mesmo no repositório oficial deles que utiliza o Subversion.

Eles utilizam um esquema semelhante ao [rolling release](https://pt.wikipedia.org/wiki/Rolling_release).
