### ISSUE TITLE
ACBrOpenDelivery - Erro ao receber json array informando tipo de Erro

### ISSUE THREAD

**Issue by nelsonflaviosantos** [ProjetoACBr/ACBr#8]
No projeto de Demo: AcbrOpenDelivery_DemoVCL

Após incluir um pedido fake, e listar ele com o botão Polling e depois pego o seu "Order ID", na aba Orders (Pedidos) é clicado no botão "Get Order details" com o o "Order ID" informado.

Depois que puxou os detalhes, é aguardado um tempo...

Supondo que passe do tempo limite, e não possa mais cancelar remotamente...

É tentado clicar em "Confirm", logicamente para confirmar o pedido. 

É retornado uma mensagem de erro em json:
         '[{"code":501,"message":"Invalid Status"}]'

Até aqui, tudo certo pois o status não pode mais ser modificado para confirmado, pois excedeu o tempo.

Só que no código é gerado a exceção: 
   "Invalid class typecast"

Esse erro ocorre na função: "TACBrJSONObject.Parse" que redireciona para a 
"TACBrJSONObject.CreateJsonObject", que ao receber o texto do json, 
esta tentando transformar o json acima, em um TJsonObject (Simples), 
mas ele é um JsonArray. 

E ai que ocorre o erro, pois não é possível transformar.

Isso ocorre ao tentar executar:
   Result := TJsonObject.Parse(AJsonString) as TJsonObject

Finalizando no bloco da exception.

Fato observado, é que ao retornar algo que NÃO seja um JsonArray, então Não ocorrerá o erro, por exemplo,
se for retornado:
	{"code":501,"message":"Invalid Status"}
	< observe que não é um json array, e sim um json simples >
Nesse caso, NÃO é gerado uma exceção e o código executa sem erros.

No entanto, conforme documentação da opendelivery, é sempre retornado um JsonArray para erro 501.
Portanto, precisamos de uma correção no código.

Observação: esta ativa a diretiva "USE_JSONDATAOBJECTS_UNIT"

![Captura de tela 2022-11-10 162905](https://user-images.githubusercontent.com/58990431/201188576-4221efbd-5961-44eb-a69e-dded388f9a2e.png)

**Comment by claytonaalves** [comment]
@nelsonflaviosantos é melhor você postar esse problema no [fórum do ACBr](https://www.projetoacbr.com.br/forum/).

Lá é o local oficial para relatar problemas.
